project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.ipynb
      - href: slides/slides.ipynb
        text: slides

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    code-fold: true
  revealjs:
    theme: dark
    transition: slide
    incremental: true
    slide-number: true

bibliography: reference.bib






